# Generated by Django manual assembly

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("issuer", models.CharField(max_length=150)),
                ("date_issued", models.DateField()),
                ("image", models.ImageField(help_text="Image copy of the certificate", upload_to="certificates/")),
                ("verification_url", models.URLField(blank=True, help_text="URL to verify certificate legitimacy online")),
            ],
            options={
                "ordering": ["-date_issued"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("institution", models.CharField(max_length=200)),
                ("degree", models.CharField(max_length=150)),
                ("field_of_study", models.CharField(blank=True, max_length=150)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False, verbose_name="Currently studying here")),
                ("description", models.TextField(blank=True, help_text="Extra details or achievements")),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("title", models.CharField(help_text="e.g., Python Automation Engineer & Django Developer", max_length=200)),
                ("bio", models.TextField(help_text="Short introductory bio for hero section")),
                ("summary", models.TextField(help_text="Detailed professional summary for About section")),
                ("profile_photo", models.ImageField(blank=True, help_text="Hero section image", null=True, upload_to="profile/")),
                ("about_photo", models.ImageField(blank=True, help_text="About section image", null=True, upload_to="profile/")),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("location", models.CharField(help_text="e.g., Gujarat, India", max_length=150)),
                ("github_username", models.CharField(blank=True, help_text="Used to show custom GitHub profile information", max_length=100)),
                ("visitor_count", models.IntegerField(default=0, help_text="Tracks total views on the portfolio")),
                ("quick_facts", models.TextField(blank=True, help_text="Key-value style or points, one per line.")),
                ("meta_title", models.CharField(blank=True, help_text="SEO Title Tag", max_length=200)),
                ("meta_description", models.TextField(blank=True, help_text="SEO Meta Description")),
                ("meta_keywords", models.CharField(blank=True, help_text="SEO Meta Keywords (comma-separated)", max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("file", models.FileField(upload_to="resumes/")),
                ("is_active", models.BooleanField(default=True, help_text="If checked, this resume will be active copy downloadable on the site.")),
                ("uploaded_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(help_text="Short explanation of what this service offers")),
                ("icon_class", models.CharField(help_text="FontAwesome icon class name. E.g., 'fa-solid fa-code'", max_length=100)),
                ("order", models.IntegerField(default=0, help_text="Display order")),
            ],
            options={
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("platform_name", models.CharField(help_text="e.g. LinkedIn, GitHub, Instagram, Email", max_length=100)),
                ("url", models.CharField(help_text="Full link URL", max_length=250)),
                ("icon_class", models.CharField(help_text="FontAwesome class. E.g., 'fa-brands fa-linkedin'", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("image", models.ImageField(help_text="Mockup / preview image", upload_to="projects/")),
                ("description", models.TextField(help_text="Short description displayed on project card grids")),
                ("detail_description", models.TextField(blank=True, help_text="Detailed HTML/Markdown/Text description shown on project details page")),
                ("tech_stack", models.CharField(help_text="Comma separated tech stack. E.g., 'Django, Selenium, SQLite, Bootstrap 5'", max_length=300)),
                ("github_url", models.URLField(blank=True, verbose_name="GitHub Repository URL")),
                ("live_url", models.URLField(blank=True, verbose_name="Live Demo URL")),
                ("featured", models.BooleanField(default=False, help_text="Show in featured list or priority sections")),
                ("order", models.IntegerField(default=0, help_text="Display order, smaller numbers show first")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("category", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="projects", to="main.category")),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("proficiency", models.IntegerField(default=80, help_text="Percentage value from 0 to 100")),
                ("icon_class", models.CharField(blank=True, help_text="FontAwesome class name, e.g., 'fa-brands fa-python'", max_length=100)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="skills", to="main.category")),
            ],
            options={
                "ordering": ["category", "-proficiency", "name"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("company", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=150)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False, verbose_name="Currently working here")),
                ("description", models.TextField(help_text="List duties and achievements. Separate points by double new lines (\n\n) or HTML break tags.")),
                ("skills_used", models.ManyToManyField(blank=True, related_name="experiences", to="main.skill")),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
    ]
