# Generated by Django 6.0.6 on 2026-07-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="quick_facts",
            field=models.TextField(
                blank=True,
                help_text="Key-value style or points, one per line. E.g. 'Completed Projects: 30+' or 'Automation scripts: 150+'",
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="If checked, this resume will be the active copy downloadable on the site.",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="icon_class",
            field=models.CharField(
                help_text="FontAwesome icon class name. E.g., 'fa-solid fa-code' or 'fa-brands fa-searchengin'",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="sociallink",
            name="icon_class",
            field=models.CharField(
                help_text="FontAwesome class. E.g., 'fa-brands fa-linkedin', 'fa-regular fa-envelope'",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="sociallink",
            name="url",
            field=models.CharField(
                help_text="Full link URL (use mailto:email@domain.com for email links)",
                max_length=250,
            ),
        ),
    ]
