"""
Django settings for portfolio project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-set1b)gq6qs*6ig1tdcsdigy*c91&^xlzb^r4#7a8vnzi(%=$z")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "unfold",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "main.apps.MainConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "portfolio.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "main.context_processors.global_context",  # Injects Profile, SocialLinks, Resume globally
            ],
        },
    },
]

WSGI_APPLICATION = "portfolio.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# import os
# import dj_database_url

# DATABASE_URL = os.environ.get("DATABASE_URL")

# if DATABASE_URL:
#     DATABASES["default"] = dj_database_url.parse(
#         DATABASE_URL,
#         conn_max_age=600,
#         ssl_require=False,
#     )


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Security Settings for production readiness
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True


from django.urls import reverse_lazy

# Unfold Custom Admin Theme Configuration
UNFOLD = {
    "SITE_TITLE": "Dhruv Chavda Admin",
    "SITE_HEADER": "Dhruv Chavda",
    "SITE_SYMBOL": "code",
    "SHOW_HISTORY": True,
    "SHOW_SIDEBAR": True,
    "STYLES": [
        lambda request: "/static/css/admin_custom.css",
    ],
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Overview & Messages",
                "separator": True,
                "items": [
                    {
                        "title": "Overview",
                        "icon": "grid_view",
                        "link": reverse_lazy("admin:index"),
                    },
                    {
                        "title": "Contact Messages",
                        "icon": "mail",
                        "link": reverse_lazy("admin:main_contactmessage_changelist"),
                    },
                ],
            },
            {
                "title": "Portfolio Management",
                "separator": True,
                "items": [
                    {
                        "title": "Profiles",
                        "icon": "person",
                        "link": reverse_lazy("admin:main_profile_changelist"),
                    },
                    {
                        "title": "Projects",
                        "icon": "folder_shared",
                        "link": reverse_lazy("admin:main_project_changelist"),
                    },
                    {
                        "title": "Skills",
                        "icon": "construction",
                        "link": reverse_lazy("admin:main_skill_changelist"),
                    },
                    {
                        "title": "Categories",
                        "icon": "sell",
                        "link": reverse_lazy("admin:main_category_changelist"),
                    },
                    {
                        "title": "Experiences",
                        "icon": "work",
                        "link": reverse_lazy("admin:main_experience_changelist"),
                    },
                    {
                        "title": "Educations",
                        "icon": "school",
                        "link": reverse_lazy("admin:main_education_changelist"),
                    },
                    {
                        "title": "Certificates",
                        "icon": "verified",
                        "link": reverse_lazy("admin:main_certificate_changelist"),
                    },
                    {
                        "title": "Services",
                        "icon": "design_services",
                        "link": reverse_lazy("admin:main_service_changelist"),
                    },
                    {
                        "title": "Resumes",
                        "icon": "description",
                        "link": reverse_lazy("admin:main_resume_changelist"),
                    },
                    {
                        "title": "Social Links",
                        "icon": "link",
                        "link": reverse_lazy("admin:main_sociallink_changelist"),
                    },
                ],
            },
            {
                "title": "Access Control",
                "separator": True,
                "items": [
                    {
                        "title": "Users",
                        "icon": "people",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": "Groups",
                        "icon": "groups",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
        ],
    },
}

